# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('location', models.CharField(default='', max_length=255)),
                ('capacity', models.FloatField(default=0)),
                ('hour_from', models.TimeField()),
                ('hour_to', models.TimeField()),
                ('insumo', models.ManyToManyField(to='hcmfront_app.Insumo')),
            ],
        ),
    ]
