# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insumo',
            new_name='Supply',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='insumo',
            new_name='supply',
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
