# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0003_auto_20170827_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
