# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0004_auto_20170827_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
