# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0005_auto_20170827_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
    ]
