# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-04 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0007_auto_20170902_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
    ]
