# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0009_auto_20170904_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation_Status',
            new_name='Reservation_Priority',
        ),
    ]
