# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0012_auto_20170906_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='priority',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hcmfront_app.Reservation_Priority'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hcmfront_app.Reservation_Status'),
        ),
    ]
