# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-08 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront_app', '0017_auto_20170908_0022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationRequest',
            new_name='Reservation_Request',
        ),
    ]
